pipeline {

  agent {     label 'terraform'   }

  parameters {
    string(name: 'FORCE_PROJECT_ID', defaultValue: 'ruta2-303211', description: 'Use Google Project ID despite the branch name')
  }
  environment {
    PROJECT_ID = '${FORCE_PROJECT_ID}' //or(params.FORCE_PROJECT_ID, inferProject('ss-pp-build-d'))
    REGION = 'us-central1'
    ZONE = 'us-central1-c'
    GOOGLE_APPLICATION_CREDENTIALS = credentials('terraform-auth')
  }  
  stages {
    stage('Terraform') {
      steps {
        container('terraform') {
          dir("infrastructure/pheonix") {
            sh "terraform --version"
            sh "terraform init -lock-timeout=60s -no-color -backend-config=bucket=${PROJECT_ID}-terraform-state"
            sh "terraform plan -lock-timeout=60s -no-color" +
                " -var project=${PROJECT_ID}" +
                " -var region=${REGION}" +
                " -var zone=${ZONE}"
            sh "terraform apply -lock-timeout=60s -no-color -auto-approve" +
                " -var project=${PROJECT_ID}" +
                " -var region=${REGION}" +
                " -var zone=${ZONE}"
          }
        }
      }
    }
  }
}
